package com.bond.bondbuddy.components

const val EXPAND_ANIMATION_DURATION = 300
const val COLLAPSE_ANIMATION_DURATION = 300
const val FADE_IN_ANIMATION_DURATION = 300
const val FADE_OUT_ANIMATION_DURATION = 300

val GeoStates: HashMap<String, String> = hashMapOf(
    Pair("AL","Alabama"),
    Pair("AK","Alaska"),
    Pair("AZ","Arizona"),
    Pair("AR","Arkansas"),
    Pair("CA","California"),
    Pair("CO","Colorado"),
    Pair("CT","Connecticut"),
    Pair("DE","Delaware"),
    Pair("DC","District of Columbia"),
    Pair("FL","Florida"),
    Pair("GA","Georgia"),
    Pair("HI","Hawaii"),
    Pair("ID","Idaho"),
    Pair("IL","Illinois"),
    Pair("IN","Indiana"),
    Pair("IA","Iowa"),
    Pair("KS","Kansas"),
    Pair("KY","Kentucky"),
    Pair("LA","Louisiana"),
    Pair("ME","Maine"),
    Pair("MD","Maryland"),
    Pair("MA","Massachusetts"),
    Pair("MI","Michigan"),
    Pair("MN","Minnesota"),
    Pair("MS","Mississippi"),
    Pair("MO","Missouri"),
    Pair("MT","Montana"),
    Pair("NE","Nebraska"),
    Pair("NV","Nevada"),
    Pair("NH","New Hampshire"),
    Pair("NJ","New Jersey"),
    Pair("NM","New Mexico"),
    Pair("NY","New York"),
    Pair("NC","North Carolina"),
    Pair("ND","North Dakota"),
    Pair("OH","Ohio"),
    Pair("OK","Oklahoma"),
    Pair("OR","Oregon"),
    Pair("PA","Pennsylvania"),
    Pair("PR","Puerto Rico"),
    Pair("RI","Rhode Island"),
    Pair("SC","South Carolina"),
    Pair("SD","South Dakota"),
    Pair("TN","Tennessee"),
    Pair("TX","Texas"),
    Pair("VI","U.S. Virgin Islands"),
    Pair("UT","Utah"),
    Pair("VT","Vermont"),
    Pair("VA","Virginia"),
    Pair("WA","Washington"),
    Pair("WV","West Virginia"),
    Pair("WI","Wisconsin"),
    Pair("WY","Wyoming"),
)


